#!/bin/bash

# Update package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a basic HTML page with "Hello World!"
echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html

# Restart Nginx
killall -s HUP nginx >/dev/null 2>&1 || true
